In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os 

# # Load the two datasets
# channels_df = pd.read_csv('dataset/channels.csv')
# videos_df = pd.read_csv('dataset/videos.csv')

# # Merge the two datasets based on the common field "Channel Title"
# merged_df = pd.merge(channels_df, videos_df, on='channel_title')

In [5]:
# merged_df.to_csv('Merged_Youtube_Dataset.csv', index=False)

In [6]:
import pandas as pd

# Load the CSV file into a pandas DataFrame
df = pd.read_csv('dataset/Merged_Youtube_Dataset.csv')

# Drop any rows with missing values
df.dropna(inplace=True)

# Remove any leading or trailing whitespace in all columns
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Convert categorical columns to numerical using one-hot encoding
#df = pd.get_dummies(df, columns=['category'])

# Normalize numerical columns to a range of 0-1
# df[numerical_cols] = (df[numerical_cols] - df[numerical_cols].min()) / (df[numerical_cols].max() - df[numerical_cols].min())

# # Save the preprocessed DataFrame to a new CSV file
# df.to_csv('preprocessed_data.csv', index=False)

In [7]:
import pandas as pd

# read the CSV file into a dataframe
df = pd.read_csv('dataset/Merged_Youtube_Dataset.csv')

# select the columns you want to drop
columns = ['Unnamed: 0_x', 'Unnamed: 0.1_x', 'channel_id','description_x','created_time','uploads','Unnamed0y','Unnamed0.1y','index','other_links','thumbnail','description_y','video_id']


# drop the selected columns from the dataframe
df = df.drop(columns=columns)

# save the new dataframe to a new CSV file
df.to_csv('new_ds.csv', index=False)

In [8]:
df = pd.read_csv('dataset/new_ds.csv')

In [9]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Define a function to get the sentiment score and label
def get_sentiment(title):
    score = analyzer.polarity_scores(title)['compound']
    if score > 0.05:
        return 1
    elif score < -0.05:
        return 0
    else:
        return 2

# Apply the sentiment analysis function to the title column and create a new column for the sentiment label
sentiments = []
for title in df['title']:
    sentiment = get_sentiment(title)
    sentiments.append(sentiment)
df['SentimentTitle'] = sentiments

# Save the updated dataframe to a new file
# df.to_csv('updated_dataset.csv', index=False)

In [10]:
df = df.drop('title',axis = 1)
df.head()

,channel_title,view_count_x,subscriber_count,video_count,video_id,category_id,tags,duration,view_count_y,likes,comments,upload_time,topic_categories,Comments,SentimentTitle
0,Onkiify,1443714,4820,193,vQ8_F8Ys4o0,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",PT3M49S,1881,112,31,2022-06-25T12:31:21Z,"['https://en.wikipedia.org/wiki/Action_game', ...",[''],0
1,Onkiify,1443714,4820,193,OIedwQ0103g,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",PT4M8S,3206,172,38,2022-06-22T12:33:21Z,"['https://en.wikipedia.org/wiki/Action_game', ...","['RIP eddie guerrero 1967-2005', 'I love this ...",1
2,Onkiify,1443714,4820,193,9-mpkWQf-cw,20,"['valorant', 'valorant riot games', 'valorant ...",PT5M32S,536,28,38,2022-10-16T12:27:44Z,"['https://en.wikipedia.org/wiki/Action_game', ...",['Finally you are back kaha the itne din se b...,1
3,Onkiify,1443714,4820,193,NQcC7k9Ufn4,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",PT3M55S,2744,145,28,2022-06-16T12:26:15Z,"['https://en.wikipedia.org/wiki/Action_game', ...","['I miss ultimate warrior rip ', 'I ultimate ...",1
4,Onkiify,1443714,4820,193,_lLJuGpwHac,20,"['valorant', 'valorant riot games', 'valorant ...",PT2M31S,212,13,14,2023-03-05T08:28:32Z,"['https://en.wikipedia.org/wiki/Action_game', ...","['We miss your wwe undefeated videos', 'Hey on...",0

In [11]:
df = df.drop('video_id',axis = 1)
df.head()

,channel_title,view_count_x,subscriber_count,video_count,category_id,tags,duration,view_count_y,likes,comments,upload_time,topic_categories,Comments,SentimentTitle
0,Onkiify,1443714,4820,193,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",PT3M49S,1881,112,31,2022-06-25T12:31:21Z,"['https://en.wikipedia.org/wiki/Action_game', ...",[''],0
1,Onkiify,1443714,4820,193,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",PT4M8S,3206,172,38,2022-06-22T12:33:21Z,"['https://en.wikipedia.org/wiki/Action_game', ...","['RIP eddie guerrero 1967-2005', 'I love this ...",1
2,Onkiify,1443714,4820,193,20,"['valorant', 'valorant riot games', 'valorant ...",PT5M32S,536,28,38,2022-10-16T12:27:44Z,"['https://en.wikipedia.org/wiki/Action_game', ...",['Finally you are back kaha the itne din se b...,1
3,Onkiify,1443714,4820,193,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",PT3M55S,2744,145,28,2022-06-16T12:26:15Z,"['https://en.wikipedia.org/wiki/Action_game', ...","['I miss ultimate warrior rip ', 'I ultimate ...",1
4,Onkiify,1443714,4820,193,20,"['valorant', 'valorant riot games', 'valorant ...",PT2M31S,212,13,14,2023-03-05T08:28:32Z,"['https://en.wikipedia.org/wiki/Action_game', ...","['We miss your wwe undefeated videos', 'Hey on...",0

In [12]:
def convert_duration(duration):
    # remove 'PT' and 'S' from the duration string
    duration = duration.strip('PT').strip('S')
    
    # check if duration contains 'M' character
    if 'M' in duration:
        # split the duration into minutes and seconds
        minutes, seconds = duration.split('M')
        # convert minutes and seconds to integers
        minutes = int(minutes) if minutes.isdigit() else 0
        seconds = int(seconds) if seconds.isdigit() else 0
    else:
        # set minutes to 0 and convert seconds to integer
        minutes = 0
        seconds = int(duration) if duration.isdigit() else 0
        
    minutes = minutes *60 
    seconds = minutes+seconds 
    return seconds

In [13]:
# df['engagement_rate'] = (df['view_count_y'] + df[''] + df['comments'] + df['shares']) / df['subs']
# df['engagement_rate'].head

In [14]:
df["duration_re"] = df["duration"].apply(convert_duration)
df = df.drop("duration",axis = 1)
df.head()

,channel_title,view_count_x,subscriber_count,video_count,category_id,tags,view_count_y,likes,comments,upload_time,topic_categories,Comments,SentimentTitle,duration_re
0,Onkiify,1443714,4820,193,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",1881,112,31,2022-06-25T12:31:21Z,"['https://en.wikipedia.org/wiki/Action_game', ...",[''],0,229
1,Onkiify,1443714,4820,193,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",3206,172,38,2022-06-22T12:33:21Z,"['https://en.wikipedia.org/wiki/Action_game', ...","['RIP eddie guerrero 1967-2005', 'I love this ...",1,248
2,Onkiify,1443714,4820,193,20,"['valorant', 'valorant riot games', 'valorant ...",536,28,38,2022-10-16T12:27:44Z,"['https://en.wikipedia.org/wiki/Action_game', ...",['Finally you are back kaha the itne din se b...,1,332
3,Onkiify,1443714,4820,193,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",2744,145,28,2022-06-16T12:26:15Z,"['https://en.wikipedia.org/wiki/Action_game', ...","['I miss ultimate warrior rip ', 'I ultimate ...",1,235
4,Onkiify,1443714,4820,193,20,"['valorant', 'valorant riot games', 'valorant ...",212,13,14,2023-03-05T08:28:32Z,"['https://en.wikipedia.org/wiki/Action_game', ...","['We miss your wwe undefeated videos', 'Hey on...",0,151

In [15]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

def get_sentiment(comments):
    # Initialize the sentiment analyzer
    analyzer = SentimentIntensityAnalyzer()
    
    # Initialize the sentiment counts
    pos_count = 0
    neg_count = 0
    neu_count = 0

    # Loop through each comment and compute its sentiment score
    for comment_str in comments:
        # Split the comma separated strings into individual strings
        comment_list = comment_str.split(',')
        
        for comment in comment_list:
            # Compute the sentiment score of the comment
            scores = analyzer.polarity_scores(comment)
            sentiment_score = scores["compound"]
        
            # Classify the comment as positive, negative, or neutral based on the sentiment score
            if sentiment_score > 0.05:
                #print(f"{comment} --> Positive sentiment")
                pos_count += 1
            elif sentiment_score < -0.05:
                #print(f"{comment} --> Negative sentiment")
                neg_count += 1
            else:
                #print(f"{comment} --> Neutral sentiment")
                neu_count += 1

    # Return the maximum count among positive, negative, and neutral sentiments
    mean = np.mean([pos_count, neg_count, neu_count])
    return mean

In [16]:
df['Sen_Com'] = df["Comments"].apply(get_sentiment)

In [17]:
df['Sen_Com']/1000

0      0.001333
1      0.598667
2      0.803667
3      0.492667
4      0.348333
         ...
466    0.959000
467    1.356333
468    1.158667
469    0.797333
470    0.912000
Name: Sen_Com, Length: 471, dtype: float64

In [20]:
import pandas as pd
import re

filename = "new_ds.csv"
column_name = "topic_categories"

# Read the CSV file into a Pandas DataFrame
df = pd.read_csv(filename)

# Remove URLs ending with "wiki/" from the specified column using regular expressions
df[column_name] = df[column_name].apply(lambda x: re.sub(r'http\S+wiki/', '', str(x)))

# Print the updated column
print(df[column_name].head(10))

0    ['Action_game', 'Sports_game', 'Video_game_cul...
1    ['Action_game', 'Sports_game', 'Video_game_cul...
2                ['Action_game', 'Video_game_culture']
3    ['Action_game', 'Sports_game', 'Video_game_cul...
4    ['Action_game', 'Role-playing_video_game', 'Vi...
5                ['Sports_game', 'Video_game_culture']
6                            ['Lifestyle_(sociology)']
7                ['Sports_game', 'Video_game_culture']
8    ['Action_game', 'Role-playing_video_game', 'Vi...
9    ['Action_game', 'Sports_game', 'Video_game_cul...
Name: topic_categories, dtype: object

In [21]:
import pandas as pd

# Read the CSV file into a Pandas DataFrame
df = pd.read_csv("new_ds.csv")

# Split the strings in the column into lists
df["topic_categories"] = df["topic_categories"].str.split(",")

# Get all unique strings in the column
unique_strings = pd.Series(df["topic_categories"].sum()).unique()

# Assign a unique value to each unique string using factorize()
string_to_value = pd.Series(pd.factorize(unique_strings)[0], index=unique_strings).to_dict()

# Map each string in the column to its assigned value
df["topic_categories"] = df["topic_categories"].apply(lambda x: [string_to_value[i] for i in x])

# Print the updated column
print(df["topic_categories"].head(10))

0    [0, 1, 2]
1    [0, 1, 2]
2       [0, 2]
3    [0, 1, 2]
4    [0, 3, 2]
5       [4, 2]
6          [5]
7       [4, 2]
8    [0, 3, 2]
9    [0, 1, 2]
Name: topic_categories, dtype: object

In [22]:
df.head()

,channel_title,view_count_x,subscriber_count,video_count,title,category_id,tags,duration,view_count_y,likes,comments,upload_time,topic_categories,Comments
0,Onkiify,1443714,4820,193,John Cena vs Randy Savage | Dream Match EP04 |...,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",PT3M49S,1881,112,31,2022-06-25T12:31:21Z,"[0, 1, 2]",['']
1,Onkiify,1443714,4820,193,Seth 'Freakin' Rollins vs Eddie Guerrero | Dre...,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",PT4M8S,3206,172,38,2022-06-22T12:33:21Z,"[0, 1, 2]","['RIP eddie guerrero 1967-2005', 'I love this ..."
2,Onkiify,1443714,4820,193,RAZE TO THE RESCUE | VALORANT 5V5 GAMEPLAY,20,"['valorant', 'valorant riot games', 'valorant ...",PT5M32S,536,28,38,2022-10-16T12:27:44Z,"[0, 2]",['Finally you are back kaha the itne din se b...
3,Onkiify,1443714,4820,193,Edge vs The Ultimate Warrior | Dream Match EP0...,20,"['wwe undefeated', 'wwe undefeated gameplay', ...",PT3M55S,2744,145,28,2022-06-16T12:26:15Z,"[0, 1, 2]","['I miss ultimate warrior rip ', 'I ultimate ..."
4,Onkiify,1443714,4820,193,YORU - I'LL FIGHT EVERYBODY | VALORANT GAMEPLAY,20,"['valorant', 'valorant riot games', 'valorant ...",PT2M31S,212,13,14,2023-03-05T08:28:32Z,"[0, 3, 2]","['We miss your wwe undefeated videos', 'Hey on..."

In [28]:
df["upload_time_copy"] = df["upload_time"]
df["upload_time_copy1"] = df["upload_time"]
df["upload_time_copy2"] = df["upload_time"]

0      2022-06-25T12:31:21Z
1      2022-06-22T12:33:21Z
2      2022-10-16T12:27:44Z
3      2022-06-16T12:26:15Z
4      2023-03-05T08:28:32Z
               ...
466    2023-03-24T14:00:22Z
467    2023-03-21T14:00:40Z
468    2023-02-24T05:30:01Z
469    2023-03-26T14:00:32Z
470    2023-03-29T14:00:29Z
Name: upload_time_copy, Length: 471, dtype: object

In [29]:
import pandas as pd

filename = "new_ds.csv"
column_name = "upload_time_copy1"

# Read the CSV file into a Pandas DataFrame
df = pd.read_csv(filename)

# Remove everything before "T" in the timestamp
df[column_name] = [column_name].apply(lambda x: str(x)[11:13])

# Print the updated column
print(df[column_name].head(10))

AttributeError: 'list' object has no attribute 'apply'

In [27]:
import pandas as pd

filename = "new_ds.csv"
column_name = "upload_time_copy"

# Read the CSV file into a Pandas DataFrame
df = pd.read_csv(filename)

# Remove everything before "T" in the timestamp
df[column_name] = df[column_name].apply(lambda x: str(x)[8:10])

# Print the updated column
print(df[column_name].head(10))

KeyError: 'upload_time_copy'

In [ ]:
df["upload_day"] = df["upload_time_copy"].astype(int)

In [ ]:
df["upload_day"] = np.array(df["upload_day"])

In [ ]:
type(df["upload_day"])

In [ ]:
import pandas as pd

filename = "new_ds.csv"
column_name = "upload_time_copy1"

# Read the CSV file into a Pandas DataFrame
df = pd.read_csv(filename)

# Remove everything before "T" in the timestamp
df[column_name] = df[column_name].apply(lambda x: str(x)[5:7])

# Print the updated column
print(df[column_name].head(10))

In [ ]:
df["upload_month"] = df["upload_time_copy1"].astype(int)

In [ ]:
df["upload_month"] = np.array(df["upload_month"])

In [ ]:
df["upload_month"]

In [ ]:
df.head()